# Generated by Django 4.0.5 on 2022-07-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockDeviceStateInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=32, verbose_name='')),
                ('clk_type', models.IntegerField(verbose_name='')),
                ('brightness', models.IntegerField(verbose_name='')),
                ('time_zone', models.IntegerField(verbose_name='')),
                ('time_fmt', models.IntegerField(verbose_name='')),
                ('run_mode', models.IntegerField(verbose_name='')),
                ('ntp_period', models.IntegerField(verbose_name='')),
                ('check_period', models.IntegerField(verbose_name='')),
                ('counter_unixtime', models.IntegerField(verbose_name='')),
                ('counter_init_value', models.IntegerField(verbose_name='')),
                ('counter_alarm_time', models.IntegerField(verbose_name='')),
                ('clk_last_recv_time', models.IntegerField(verbose_name='')),
                ('clk_id', models.IntegerField(verbose_name='')),
                ('clk_ipaddr', models.CharField(max_length=16, verbose_name='')),
                ('clk_socket', models.IntegerField(verbose_name='')),
                ('position', models.CharField(max_length=128, verbose_name='')),
                ('state_code', models.IntegerField(verbose_name='')),
                ('clk_note', models.CharField(max_length=64, verbose_name='')),
                ('cmd_state', models.IntegerField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Clock Info',
                'verbose_name_plural': 'Clock Info',
            },
        ),
    ]
