# Generated by Django 4.0.5 on 2022-07-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockLogInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(default='', max_length=32, verbose_name='')),
                ('msg_code', models.IntegerField(default='', verbose_name='')),
                ('log_unixtime', models.IntegerField(default='', verbose_name='')),
            ],
            options={
                'verbose_name': 'Clock Log Info',
                'verbose_name_plural': 'Clock Log Info',
            },
        ),
        migrations.CreateModel(
            name='ClockTempRegInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(default='', max_length=32, verbose_name='')),
                ('clk_type', models.IntegerField(default='', verbose_name='')),
                ('brightness', models.IntegerField(default='', verbose_name='')),
                ('time_zone', models.IntegerField(default='', verbose_name='')),
                ('time_fmt', models.IntegerField(default='', verbose_name='')),
                ('run_mode', models.IntegerField(default='', verbose_name='')),
                ('ntp_period', models.IntegerField(default='', verbose_name='')),
                ('check_period', models.IntegerField(default='', verbose_name='')),
                ('counter_unixtime', models.IntegerField(default='', verbose_name='')),
                ('counter_init_value', models.IntegerField(default='', verbose_name='')),
                ('counter_alarm_time', models.IntegerField(default='', verbose_name='')),
                ('clk_last_recv_time', models.IntegerField(default='', verbose_name='')),
                ('clk_id', models.IntegerField(default='', verbose_name='')),
                ('clk_ipaddr', models.CharField(default='', max_length=16, verbose_name='')),
                ('register', models.IntegerField(default='', verbose_name='')),
            ],
            options={
                'verbose_name': 'Clock Temp Reg Info',
                'verbose_name_plural': 'Clock Temp Reg Info',
            },
        ),
        migrations.CreateModel(
            name='CounterClkInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(default='', max_length=32, verbose_name='')),
                ('group_id', models.IntegerField(default='', verbose_name='')),
                ('counter_unixtime', models.IntegerField(default='', verbose_name='')),
                ('counter_init_value', models.IntegerField(default='', verbose_name='')),
                ('counter_alarm_time', models.IntegerField(default='', verbose_name='')),
            ],
            options={
                'verbose_name': 'Counter Clock Info',
                'verbose_name_plural': 'Counter Clock Info',
            },
        ),
        migrations.CreateModel(
            name='CounterGroupInfo',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='', max_length=64, verbose_name='')),
            ],
            options={
                'verbose_name': 'Counter Group Info',
                'verbose_name_plural': 'Counter Group Info',
            },
        ),
        migrations.CreateModel(
            name='MsgInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg_code', models.IntegerField(default='', verbose_name='')),
                ('msg_name_cn', models.CharField(default='', max_length=64, verbose_name='')),
                ('msg_name_en', models.CharField(default='', max_length=64, verbose_name='')),
                ('msg_name_fr', models.CharField(default='', max_length=64, verbose_name='')),
            ],
            options={
                'verbose_name': 'Message Info',
                'verbose_name_plural': 'Message Info',
            },
        ),
        migrations.CreateModel(
            name='StateNoteInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_code', models.IntegerField(default='', verbose_name='')),
                ('state_name_cn', models.CharField(default='', max_length=64, verbose_name='')),
                ('state_name_en', models.CharField(default='', max_length=64, verbose_name='')),
                ('state_name_fr', models.CharField(default='', max_length=64, verbose_name='')),
                ('state_note', models.CharField(default='', max_length=64, verbose_name='')),
            ],
            options={
                'verbose_name': 'State Note Info',
                'verbose_name_plural': 'State Note Info',
            },
        ),
        migrations.CreateModel(
            name='TimeZoneInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_zone', models.IntegerField(default='', verbose_name='')),
                ('offset', models.IntegerField(default='', verbose_name='')),
                ('name', models.CharField(default='', max_length=128, verbose_name='')),
            ],
            options={
                'verbose_name': 'Time Zone Info',
                'verbose_name_plural': 'Time Zone Info',
            },
        ),
        migrations.AddField(
            model_name='clockdevicestateinfo',
            name='connect',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='brightness',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='check_period',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='clk_id',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='clk_ipaddr',
            field=models.CharField(default='', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='clk_last_recv_time',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='clk_note',
            field=models.CharField(default='', max_length=64, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='clk_socket',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='clk_type',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='cmd_state',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='counter_alarm_time',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='counter_init_value',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='counter_unixtime',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='imei',
            field=models.CharField(default='', max_length=32, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='ntp_period',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='position',
            field=models.CharField(default='', max_length=128, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='run_mode',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='state_code',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='time_fmt',
            field=models.IntegerField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clockdevicestateinfo',
            name='time_zone',
            field=models.IntegerField(default='', verbose_name=''),
        ),
    ]
