<?php

declare(strict_types=1);

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('data_types')->delete();

        \DB::table('data_types')->insert([
            [
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => \App\Models\User::class,
                'policy_name' => \App\Policies\UserPolicy::class,
                'controller' => \App\Http\Controllers\Admin\UserController::class,
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => null,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 00:37:07',
            ],
            [
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => \TCG\Voyager\Models\Menu::class,
                'policy_name' => null,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => null,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 00:37:07',
            ],
            [
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => \App\Models\Role::class,
                'policy_name' => null,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => null,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 00:37:07',
            ],
            [
                'name' => 'products',
                'slug' => 'products',
                'display_name_singular' => 'Product',
                'display_name_plural' => 'Products',
                'icon' => 'voyager-tree',
                'model_name' => \App\Models\Product::class,
                'policy_name' => null,
                'controller' => \App\Http\Controllers\Admin\ProductController::class,
                'description' => null,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"name","order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-09-16 19:24:20',
                'updated_at' => '2019-09-16 19:24:20',
            ],
            [
                'name' => 'product_categories',
                'slug' => 'product-categories',
                'display_name_singular' => 'Product Category',
                'display_name_plural' => 'Product Categories',
                'icon' => 'voyager-categories',
                'model_name' => \App\Models\ProductCategory::class,
                'policy_name' => null,
                'controller' => \App\Http\Controllers\Admin\ProductCategoryController::class,
                'description' => null,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"name","order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-09-16 19:24:33',
                'updated_at' => '2019-09-16 19:24:33',
            ],
            [
                'name' => 'locations',
                'slug' => 'locations',
                'display_name_singular' => 'Location',
                'display_name_plural' => 'Locations',
                'icon' => 'voyager-company',
                'model_name' => \App\Models\Location::class,
                'policy_name' => null,
                'controller' => \App\Http\Controllers\Admin\LocationController::class,
                'description' => null,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"title","order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-10-10 18:48:59',
                'updated_at' => '2019-10-10 18:48:59',
            ],
            [
                'name' => 'services',
                'slug' => 'services',
                'display_name_singular' => 'Service',
                'display_name_plural' => 'Services',
                'icon' => 'voyager-lightbulb',
                'model_name' => \App\Models\Service::class,
                'policy_name' => null,
                'controller' => \App\Http\Controllers\Admin\ServiceController::class,
                'description' => null,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"name","order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-10-10 18:48:59',
                'updated_at' => '2019-10-10 18:48:59',
            ],
            [
                'name' => 'coupons',
                'slug' => 'coupons',
                'display_name_singular' => 'Coupon',
                'display_name_plural' => 'Coupons',
                'icon' => 'voyager-tag',
                'model_name' => \App\Models\Coupon::class,
                'policy_name' => null,
                'controller' => \App\Http\Controllers\Admin\CouponController::class,
                'description' => null,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"code","order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-11-17 18:55:12',
                'updated_at' => '2019-11-17 18:55:12',
            ],
            [
                'name' => 'orders',
                'slug' => 'orders',
                'display_name_singular' => 'Order',
                'display_name_plural' => 'Orders',
                'icon' => 'voyager-basket',
                'model_name' => \App\Models\Order::class,
                'policy_name' => null,
                'controller' => \App\Http\Controllers\Admin\OrderController::class,
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => null,
                'created_at' => '2019-12-08 12:37:07',
                'updated_at' => '2019-12-08 12:37:07',
            ],
            [
                'name' => 'company_file_categories',
                'slug' => 'company-file-categories',
                'display_name_singular' => 'Company File Category',
                'display_name_plural' => 'Company File Categories',
                'icon' => 'voyager-harddrive',
                'model_name' => \App\Models\CompanyFileCategory::class,
                'policy_name' => null,
                'controller' => \App\Http\Controllers\Admin\CompanyFileCategoryController::class,
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"order","order_display_column":"name","order_direction":"asc"}',
                'created_at' => '2019-12-31 10:15:42',
                'updated_at' => '2019-12-31 10:15:42',
            ],
            [
                'name' => 'company_files',
                'slug' => 'company-files',
                'display_name_singular' => 'Company File',
                'display_name_plural' => 'Company Files',
                'icon' => 'voyager-file-text',
                'model_name' => \App\Models\CompanyFile::class,
                'policy_name' => null,
                'controller' => \App\Http\Controllers\Admin\CompanyFileController::class,
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"order","order_display_column":"name","order_direction":"asc"}',
                'created_at' => '2020-01-02 15:45:29',
                'updated_at' => '2020-01-02 15:45:29',
            ],
        ]);
    }
}
