<?php

declare(strict_types=1);

use Illuminate\Support\Facades\DB;

class DataRowsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('data_rows')->delete();

        $dataTypes = collect([
            'users',
            'menus',
            'roles',
            'products',
            'product_categories',
            'locations',
            'services',
            'coupons',
            'orders',
            'company_file_categories',
            'company_files',
        ])->reduce(function ($acc, $dataTypeName) {
            $acc[$dataTypeName] = DB::table('data_types')->where('name', $dataTypeName)->first() ?? self::dataTypeNotFound($dataTypeName);

            return $acc;
        }, []);

        DB::table('data_rows')->insert([
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'first_name',
                'type' => 'text',
                'display_name' => 'First Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"link": {"edit": "edit", "read": "show"}}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'last_name',
                'type' => 'text',
                'display_name' => 'Last Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"link": {"edit": "edit", "read": "show"}}',
                'order' => 3,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation": {"rule": "required|email:filter,rfc,dns"}}',
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => null,
                'order' => 5,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}',
                'order' => 6,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'user_belongstomany_permission_relationship',
                'type' => 'relationship',
                'display_name' => 'Additional Permissions',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\Permission","table":"permissions","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"permission_user","pivot":"1","taggable":"0"}',
                'order' => 7,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 8,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => null,
                'order' => 9,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 10,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'shipping_first_name',
                'type' => 'text',
                'display_name' => 'Shipping First Name',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'shipping_last_name',
                'type' => 'text',
                'display_name' => 'Shipping Last Name',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 12,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'shipping_address',
                'type' => 'text',
                'display_name' => 'Shipping Address',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'shipping_city',
                'type' => 'text',
                'display_name' => 'Shipping City',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 14,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'shipping_state',
                'type' => 'text',
                'display_name' => 'Shipping State',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText":"2-letter abbreviation","validation": {"rule": "max:2"}}',
                'order' => 15,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'shipping_zip',
                'type' => 'text',
                'display_name' => 'Shipping Zip',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 16,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'shipping_phone',
                'type' => 'text',
                'display_name' => 'Shipping Phone',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 17,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 18,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 19,
            ],
            [
                'data_type_id' => $dataTypes['menus']->id,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['menus']->id,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => null,
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['menus']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 3,
            ],
            [
                'data_type_id' => $dataTypes['menus']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['roles']->id,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['roles']->id,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => null,
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['roles']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 3,
            ],
            [
                'data_type_id' => $dataTypes['roles']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['roles']->id,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => null,
                'order' => 5,
            ],
            [
                'data_type_id' => $dataTypes['users']->id,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => null,
                'order' => 9,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"link": {"edit": "edit", "read": "show"}}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'product_category_id',
                'type' => 'text',
                'display_name' => 'Category',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'product_belongsto_product_category_relationship',
                'type' => 'product-category-and-prices',
                'display_name' => '',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\ProductCategory","table":"product_categories","type":"belongsTo","column":"product_category_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":null}',
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'description',
                'type' => 'rich_text_box',
                'display_name' => 'Description',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation": {"rule": "required"} }',
                'order' => 5,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'image',
                'type' => 'image_picker',
                'display_name' => 'Image',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText":"(290x220px)"}',
                'order' => 6,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'price',
                'type' => 'number',
                'display_name' => 'Price',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'num_washes',
                'type' => 'number',
                'display_name' => 'Number of Washes Included',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'price_monthly',
                'type' => 'number',
                'display_name' => 'Price Monthly',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'price_annual',
                'type' => 'number',
                'display_name' => 'Price Annually',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ],
            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ],

            [
                'data_type_id' => $dataTypes['products']->id,
                'field' => 'product_belongstomany_product_shipping_prices_relationship',
                'type' => 'product_shipping_prices',
                'display_name' => 'Shipping Price',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\ProductShippingPrice","table":"product_shipping_prices","type":"belongsToMany","column":"product_id","key":"id","label":"name","pivot_table":"","pivot":"0","taggable":"0","helperText":"Enter the price per unit you wish to charge. Prices are applied uniformly across all items in the cart based on the quantity purchased."}',
                'order' => 12,
            ],
            [
                'data_type_id' => $dataTypes['product_categories']->id,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['product_categories']->id,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"link": {"edit": "edit", "read": "show"}}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['product_categories']->id,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"unique:product_categories,slug","messages":{"unique": "Please use a unique slug."}},"slugify": {"origin": "name","forceUpdate": false}}',
                'order' => 3,
            ],
            [
                'data_type_id' => $dataTypes['product_categories']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['product_categories']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ],
            [
                'data_type_id' => $dataTypes['product_categories']->id,
                'field' => 'product_category_hasmany_product_relationship',
                'type' => 'relationship',
                'display_name' => 'Products',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Product","table":"products","type":"hasMany","column":"product_category_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":null}',
                'order' => 6,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"link": {"edit": "edit", "read": "show"}}',
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'canonical_url',
                'type' => 'canonical_url',
                'display_name' => 'Canonical URL',
                'required' => 0, // Not required because '' is a valid input value.
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'hero_image',
                'type' => 'image_picker',
                'display_name' => 'Hero Image',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText": "(1440x320px)"}',
                'order' => 3,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'site_number',
                'type' => 'text',
                'display_name' => 'Site Number',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'lng_lat',
                'type' => 'coordinates',
                'display_name' => 'Map Pin',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"onChange": "updateAddress"}',
                'order' => 5,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'address_line_1',
                'type' => 'text',
                'display_name' => 'Website Display Address (line 1)',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText": "Edit to update address appearance on the website."}',
                'order' => 6,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'address_line_2',
                'type' => 'text',
                'display_name' => 'Website Display Address (line 2)',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText": "Edit to update address appearance on the website."}',
                'order' => 7,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'phone',
                'type' => 'text',
                'display_name' => 'Phone Number',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText": "e.g. 555.555.5555", "validation": {"rule": "regex:/^[0-9]{3}[ .-]{0,}[0-9]{3}[ .-]{0,}[0-9]{4}$/"} }',
                'order' => 8,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'manager_name',
                'type' => 'text',
                'display_name' => 'Manager Name',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'manager_title',
                'type' => 'text',
                'display_name' => 'Manager Title',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'price_range',
                'type' => 'text',
                'display_name' => 'Price Range',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText":"The relative price range of a business, commonly specified by either a numerical range (for example, \"$10-15\") or a normalized number of currency signs (for example, \"$$$\")"}',
                'order' => 11,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'location_belongstomany_service_relationship',
                'type' => 'location_services',
                'display_name' => 'Services',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Service","table":"services","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"location_service","pivot":"1","taggable":"0","helperText":"Services must be added for locations to show up in search results. Please select all that apply."}',
                'order' => 12,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'meta_title',
                'type' => 'text',
                'display_name' => 'Meta Title',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'meta_description',
                'type' => 'text',
                'display_name' => 'Meta Description',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 14,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'meta_keywords',
                'type' => 'text',
                'display_name' => 'Meta Keywords',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 15,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 16,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 17,
            ],
            [
                'data_type_id' => $dataTypes['locations']->id,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 18,
            ],
            [
                'data_type_id' => $dataTypes['services']->id,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"link": {"edit": "edit", "read": "show"}}',
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['services']->id,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"unique:services,slug","messages":{"unique": "Please use a unique slug."}},"slugify": {"origin": "name","forceUpdate": false}}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['services']->id,
                'field' => 'icon_class',
                'type' => 'text',
                'display_name' => 'Icon Class',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ],
        ]);
        DB::table('data_rows')->insert([
            [
                'data_type_id' => $dataTypes['services']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['services']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 5,
            ],
            [
                'data_type_id' => $dataTypes['coupons']->id,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['coupons']->id,
                'field' => 'code',
                'type' => 'text',
                'display_name' => 'Code',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"unique:coupons,code","messages":{"unique": "Please use a unique code."}},"link": {"edit": "edit", "read": "show"}}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['coupons']->id,
                'field' => 'percent_discount',
                'type' => 'number',
                'display_name' => 'Percent Discount',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText": "From 1 to 100", "validation": {"rule": "required|numeric|between:1,100"} }',
                'order' => 3,
            ],
            [
                'data_type_id' => $dataTypes['coupons']->id,
                'field' => 'minimum_cart_total',
                'type' => 'number',
                'display_name' => 'Minimum Cart Total',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText": "In dollars", "validation": {"rule": "required|numeric|between:0,65535"} }',
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['coupons']->id,
                'field' => 'coupon_belongstomany_product_relationship',
                'type' => 'coupon_products',
                'display_name' => 'Applicable Products',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Product","table":"products","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"coupon_product","pivot":"1","taggable":null}',
                'order' => 5,
            ],
            [
                'data_type_id' => $dataTypes['coupons']->id,
                'field' => 'num_uses',
                'type' => 'number',
                'display_name' => '# of Uses',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ],
            [
                'data_type_id' => $dataTypes['coupons']->id,
                'field' => 'expires_after_num_uses',
                'type' => 'number',
                'display_name' => 'Expires After # of Uses',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText": "Limits the number of items the coupon can be applied to, across all time.", "validation": {"rule": "required|numeric|between:0,65535"} }',
                'order' => 7,
            ],
            [
                'data_type_id' => $dataTypes['coupons']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 8,
            ],
            [
                'data_type_id' => $dataTypes['coupons']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 9,
            ],
            [
                'data_type_id' => $dataTypes['coupons']->id,
                'field' => 'expires_at',
                'type' => 'timestamp',
                'display_name' => 'Expires At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => null,
                'order' => 10,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'ID',
                'required' => 0,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"link": {"read": "show"}}',
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'customer',
                'type' => 'order_customer',
                'display_name' => 'Customer',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'Customer',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation": {"rule": "required_without:user_email|not_present_with:user_email"}}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'order_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Customer',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"full_name","taggable":null}',
                'order' => 3,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'user_email',
                'type' => 'text',
                'display_name' => 'Guest Customer Email',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation": {"rule": "required_without:user_id|not_present_with:user_id"}}',
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'customer_first_name',
                'type' => 'text',
                'display_name' => 'Guest Customer First Name',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation": {"rule": "required_without:user_id|not_present_with:user_id"}}',
                'order' => 5,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'customer_last_name',
                'type' => 'text',
                'display_name' => 'Guest Customer Last Name',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation": {"rule": "required_without:user_id|not_present_with:user_id"}}',
                'order' => 6,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'shipping_full_address',
                'type' => 'order_shipping_address',
                'display_name' => 'Shipping Address',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'shipping_first_name',
                'type' => 'text',
                'display_name' => 'Shipping First Name',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'shipping_last_name',
                'type' => 'text',
                'display_name' => 'Shipping Last Name',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'shipping_address',
                'type' => 'text',
                'display_name' => 'Shipping Address',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'shipping_city',
                'type' => 'text',
                'display_name' => 'Shipping City',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'shipping_state',
                'type' => 'text',
                'display_name' => 'Shipping State',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"helperText":"2-letter abbreviation","validation": {"rule": "max:2"}}',
                'order' => 12,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'shipping_zip',
                'type' => 'text',
                'display_name' => 'Shipping Zip',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'shipping_phone',
                'type' => 'text',
                'display_name' => 'Shipping Phone',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 14,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'order_belongstomany_product_relationship',
                'type' => 'order_products',
                'display_name' => 'Products',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Product","table":"products","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"order_product","pivot":"1","taggable":null}',
                'order' => 15,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'access_token',
                'type' => 'text',
                'display_name' => 'Access Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 16,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'discount',
                'type' => 'number',
                'display_name' => 'Discount',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 17,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'sub_total',
                'type' => 'number',
                'display_name' => 'Subtotal',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 18,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'tax_rate',
                'type' => 'number',
                'display_name' => 'Tax Rate',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 19,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'shipping_price',
                'type' => 'number',
                'display_name' => 'Shipping Price',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 20,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'tax',
                'type' => 'number',
                'display_name' => 'Tax',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 21,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'total',
                'type' => 'number',
                'display_name' => 'Total',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 22,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'status',
                'type' => 'order_status',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 23,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'transaction_error',
                'type' => 'text',
                'display_name' => 'Transaction Error',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 24,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'transaction_id',
                'type' => 'text',
                'display_name' => 'Transaction ID',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 25,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 26,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'shipped_notification_sent_at',
                'type' => 'timestamp',
                'display_name' => 'Shipping Notification Sent At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 27,
            ],
            [
                'data_type_id' => $dataTypes['orders']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 28,
            ],
            [
                'data_type_id' => $dataTypes['company_file_categories']->id,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'ID',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['company_file_categories']->id,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Category Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"link": {"edit": "edit", "read": "show"}}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['company_file_categories']->id,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"unique:company_file_categories,slug","messages":{"unique": "Please use a unique slug."}},"slugify": {"origin": "name","forceUpdate": false}}',
                'order' => 3,
            ],
            [
                'data_type_id' => $dataTypes['company_file_categories']->id,
                'field' => 'company_file_category_hasmany_company_file_relationship',
                'type' => 'relationship',
                'display_name' => 'Files',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\CompanyFile","table":"company_files","type":"hasMany","column":"company_file_category_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":null}',
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['company_file_categories']->id,
                'field' => 'order',
                'type' => 'hidden',
                'display_name' => 'Order',
                'required' => 0,
                'browse' => 1,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ],
            [
                'data_type_id' => $dataTypes['company_file_categories']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 6,
            ],
            [
                'data_type_id' => $dataTypes['company_file_categories']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 7,
            ],
            [
                'data_type_id' => $dataTypes['company_files']->id,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'ID',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ],
            [
                'data_type_id' => $dataTypes['company_files']->id,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"link": {"edit": "edit", "read": "show"}}',
                'order' => 2,
            ],
            [
                'data_type_id' => $dataTypes['company_files']->id,
                'field' => 'company_file_category_id',
                'type' => 'text',
                'display_name' => 'Category',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ],
            [
                'data_type_id' => $dataTypes['company_files']->id,
                'field' => 'company_file_belongsto_company_file_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Category',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\CompanyFileCategory","table":"company_file_categories","type":"belongsTo","column":"company_file_category_id","key":"id","label":"name","pivot_table":"company_file_categories","pivot":"0","taggable":null}',
                'order' => 4,
            ],
            [
                'data_type_id' => $dataTypes['company_files']->id,
                'field' => 'path',
                'type' => 'company_file',
                'display_name' => 'File',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ],
            [
                'data_type_id' => $dataTypes['company_files']->id,
                'field' => 'thumbnail',
                'type' => 'hidden',
                'display_name' => 'Thumbnail',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ],
            [
                'data_type_id' => $dataTypes['company_files']->id,
                'field' => 'mime_type',
                'type' => 'hidden',
                'display_name' => 'MIME Type',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ],
            [
                'data_type_id' => $dataTypes['company_files']->id,
                'field' => 'order',
                'type' => 'hidden',
                'display_name' => 'Order',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ],
            [
                'data_type_id' => $dataTypes['company_files']->id,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 9,
            ],
            [
                'data_type_id' => $dataTypes['company_files']->id,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => null,
                'order' => 10,
            ],
        ]);
    }
}
