<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuItemsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('menu_items')->delete();

        DB::table('menu_items')->insert([
            /*
            [
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => null,
                'parent_id' => null,
                'order' => 1,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 00:37:07',
                'route' => 'voyager.dashboard',
                'parameters' => null,
            ],
*/
            [
                'menu_id' => 1,
                'title' => 'CONTENT',
                'url' => '',
                'target' => '_self',
                'icon_class' => null,
                'color' => null,
                'parent_id' => null,
                'order' => 1,
                'created_at' => '2019-12-13 08:44:13',
                'updated_at' => '2019-12-13 08:44:13',
                'route' => null,
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Locations',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-company',
                'color' => null,
                'parent_id' => null,
                'order' => 3,
                'created_at' => '2019-09-17 06:34:04',
                'updated_at' => '2019-09-17 06:34:04',
                'route' => 'voyager.locations.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => null,
                'parent_id' => null,
                'order' => 4,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 02:48:54',
                'route' => 'voyager.media.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'SHOPPING',
                'url' => '',
                'target' => '_self',
                'icon_class' => null,
                'color' => null,
                'parent_id' => null,
                'order' => 5,
                'created_at' => '2019-12-13 08:44:13',
                'updated_at' => '2019-12-13 08:44:13',
                'route' => null,
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Orders',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-basket',
                'color' => null,
                'parent_id' => null,
                'order' => 6,
                'created_at' => '2019-12-08 12:37:07',
                'updated_at' => '2019-12-08 12:37:07',
                'route' => 'voyager.orders.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Products',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tree',
                'color' => null,
                'parent_id' => null,
                'order' => 7,
                'created_at' => '2019-09-17 06:34:04',
                'updated_at' => '2019-09-17 06:34:04',
                'route' => 'voyager.products.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Product Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => null,
                'parent_id' => null,
                'order' => 8,
                'created_at' => '2019-09-17 06:34:04',
                'updated_at' => '2019-09-17 06:34:04',
                'route' => 'voyager.product-categories.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Coupons',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => null,
                'parent_id' => null,
                'order' => 9,
                'created_at' => '2019-11-17 18:55:12',
                'updated_at' => '2019-11-17 18:55:12',
                'route' => 'voyager.coupons.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Sales Tax',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dollar',
                'color' => null,
                'parent_id' => null,
                'order' => 10,
                'created_at' => '2019-11-19 16:52:30',
                'updated_at' => '2019-11-19 16:52:30',
                'route' => 'voyager.sales-tax.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'COMPANY FILES',
                'url' => '',
                'target' => '_self',
                'icon_class' => null,
                'color' => null,
                'parent_id' => null,
                'order' => 11,
                'created_at' => '2019-12-13 08:44:13',
                'updated_at' => '2019-12-13 08:44:13',
                'route' => null,
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Files',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => null,
                'parent_id' => null,
                'order' => 12,
                'created_at' => '2020-01-02 15:45:29',
                'updated_at' => '2020-01-02 15:45:29',
                'route' => 'voyager.company-files.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-harddrive',
                'color' => null,
                'parent_id' => null,
                'order' => 13,
                'created_at' => '2019-12-31 10:23:12',
                'updated_at' => '2019-12-31 10:23:12',
                'route' => 'voyager.company-file-categories.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'ADMIN',
                'url' => '',
                'target' => '_self',
                'icon_class' => null,
                'color' => null,
                'parent_id' => null,
                'order' => 14,
                'created_at' => '2019-12-13 08:44:13',
                'updated_at' => '2019-12-13 08:44:13',
                'route' => null,
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Services',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lightbulb',
                'color' => null,
                'parent_id' => null,
                'order' => 15,
                'created_at' => '2019-09-17 06:34:04',
                'updated_at' => '2019-09-17 06:34:04',
                'route' => 'voyager.services.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => null,
                'parent_id' => null,
                'order' => 16,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 02:48:54',
                'route' => null,
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => null,
                'parent_id' => null,
                'order' => 17,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 02:48:54',
                'route' => 'voyager.users.index',
                'parameters' => null,
            ],
        ]);

        $parentMenuItem = DB::table('menu_items')->where('title', 'Tools')->first() ?? dd('⚠️  Tools menu_item Not Found. Halting... ☠️');

        DB::table('menu_items')->insert([
            [
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => null,
                'parent_id' => $parentMenuItem->id,
                'order' => 9,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 02:49:26',
                'route' => 'voyager.roles.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => null,
                'parent_id' => $parentMenuItem->id,
                'order' => 6,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 02:49:15',
                'route' => 'voyager.menus.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => null,
                'parent_id' => $parentMenuItem->id,
                'order' => 4,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 02:49:15',
                'route' => 'voyager.database.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => null,
                'parent_id' => $parentMenuItem->id,
                'order' => 3,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 02:49:13',
                'route' => 'voyager.compass.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => null,
                'parent_id' => $parentMenuItem->id,
                'order' => 2,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 02:49:11',
                'route' => 'voyager.bread.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => null,
                'parent_id' => $parentMenuItem->id,
                'order' => 8,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 02:49:26',
                'route' => 'voyager.settings.index',
                'parameters' => null,
            ],
            [
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => null,
                'parent_id' => $parentMenuItem->id,
                'order' => 5,
                'created_at' => '2019-08-06 00:37:07',
                'updated_at' => '2019-08-06 02:49:15',
                'route' => 'voyager.hooks',
                'parameters' => null,
            ],
        ]);
    }
}
